import React from 'react';
import ReactDOM from 'react-dom';

// Convert the following JSX
// const output =
//   <div>
//     <p>React: A JavaScript library for building user interfaces</p>
//     <p>Redux: A predictable state container for JavaScript apps</p>
//     <p>Reselect: A simple selector library for Redux</p>
//   </div>;

// ReactDOM.render(output, document.getElementById('root'));

// To be generated by the use of this function
const libraries = [
  {
    title: 'React',
    description: 'A JavaScript library for building user interfaces'
  },
  {
    title: 'Redux',
    description: 'A predictable state container for JavaScript apps'
  },
  {
    title: 'Reselect',
    description: 'A simple selector library for Redux'
  }
];


const output = libraries => 
  (
    <div key={libraries.title}>
      <span>{libraries.description}</span>
    </div>
  );

const outputAsJSX = libraries.map(output);

ReactDOM.render(<div>{outputAsJSX}</div>, document.getElementById('root'));


